services:
  - type: web
    name: vfx-scraper-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SARVAM_API_KEY
        sync: false
      - key: PORT
        value: 10000
